version: '3.6'
services:
    web_service:
      container_name: web_service
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "0.0.0.0:4888:4888"
      volumes:
        - .:/app/

      environment:
        APP_HOST: 0.0.0.0
        APP_PORT: 4888
        TG_TOKEN: lalala

        POSTGRES_HOST: web_service_db
        POSTGRES_DB: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_PORT: 5432

      networks:
        - default

    web_service_db:
      image: postgres:13
      container_name: web_service_db
      environment:
        POSTGRES_DB: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_PORT: 5432
      ports:
        - "54329:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data
      networks:
        - default

volumes:
  pgdata:
